name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # Runs at the start of every 12th hour
  workflow_dispatch:
  push:
    branches:
      - main  # Replace `master` with `main` if that is your default branch

jobs:
  generate:
    permissions:
      contents: write  # Required to push the generated file to the output branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Ensures the repo is available for updates

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark  # Ensure the path is correct

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Specify the branch to push to (usually `output`)
          build_dir: dist  # Make sure the generated snake.svg is in the `dist` directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the GITHUB_TOKEN has write permissions
